'use client'
import { createContext, useEffect, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "firebase/auth";
import { app } from '@/firebase.config'
import { Box, useToast } from '@chakra-ui/react'
import { useRouter } from 'next/navigation'




// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const authContext = createContext();//Creating authContext for Context API
const auth = getAuth(app);

export default function RootLayout({ children }) {

  const [userInfo, setUserInfo] = useState(null);// user information
  const router = useRouter() // Declaring router
  const [allUser, setAllUser] = useState([]); //Information of All users
  const [frndImg, setFrndImg] = useState('')// This state contain the image of the friend with whol conversation is running. This image will be displayed on the top through the state value
  const [frndNm, setFrndNm] = useState(''); // same reasone as previous state
  const [buddyMail, setBuddyMail] = useState('') // When user choose a friend from friendlist to chat with, then that friend's mail adress stored in this state, so that, all the conversation with friend can be restored.
  const [message, setMessage] = useState('') // every single conversation.
  const [conversation, setConversation] = useState([]);// hold all the conversation
  const [sendTrigger, setSendTrigger] = useState(true);// triggered when send button is clicked

  // Feting all users information from database
  fetch('http://localhost:5000/users')
    .then(res => res.json())
    .then(data => setAllUser(data))




  // Function to register user
  const handleRegistration = (email, password) => {
    console.log(123)
    event.preventDefault();
    createUserWithEmailAndPassword(auth, email, password)
      .then((userCredential) => {
        setUserInfo(userCredential.user)
        router.push('./Home')
      })
      .catch((error) => {
        console.log(error.message);
      });
  }

  // Function to login user
  const handleLogin = (email, password) => {

    console.log(email, password)
    event.preventDefault();
    signInWithEmailAndPassword(auth, email, password)
      .then((userCredential) => {
        const user = userCredential.user;
        setUserInfo(user)

        console.log(user)
        alert('done')
      })
      .catch((error) => {
        console.log(error.message);
      });
  }

  //  Function to logout user
  const handleLogout = () => {
    signOut(auth).then(() => {
      setUserInfo('')
      router.push('./')
    }).catch((error) => {
      // An error happened.
    });
  }


 



  // observer========================================
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (userInfo) => {
      if (userInfo) {
        setUserInfo(userInfo);

      } else {
        setUserInfo(null);
      }
    });

    return () => {
      unsubscribe();
    };
  }, []);



  // These are the value that will be passed through Context API
  const value = {
    handleLogin,
    handleRegistration,
    handleLogout,
    userInfo,
    allUser,
    frndImg,
    setFrndImg,
    frndNm,
    setFrndNm,
    buddyMail,
    setBuddyMail,
    message,
    setMessage,
    conversation,
    setConversation,
    sendTrigger,
    setSendTrigger
  }

  return (
    <html lang="en">
      <body className={inter.className}>


        <authContext.Provider value={value}>
          {children}
        </authContext.Provider>



      </body>
    </html>
  )
}
