'use client'
import { createContext, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from "firebase/auth";
import { app } from '@/firebase.config'
import { Box, useToast } from '@chakra-ui/react'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const authContext = createContext();//Creating authContext for Context API
const auth = getAuth(app);

export default function RootLayout({ children }) {

  const [userInfo, setUserInfo] = useState(null);// user information

  // Function to register user
  const handleRegistration = (email, password) => {
    console.log(123)

    createUserWithEmailAndPassword(auth, email, password)
    console.log(email, password)
      .then((userCredential) => {
        setUserInfo(userCredential.user)
      })
      .catch((error) => {
        console.log(error.message);
      });
  }

  // Function to login user
  const handleLogin = (email, password) => {
    event.preventDefault();
    console.log(email, password)
    signInWithEmailAndPassword(auth, email, password)
      .then((userCredential) => {
        const user = userCredential.user;
        setUserInfo(user)

        console.log(user)
        alert('done')
      })
      .catch((error) => {
        console.log(error.message);
      });
  }

  //  Function to logout user
  const handleLogout = () =>{
    signOut(auth).then(() => {
      setUserInfo('')
      alert('successfully logout')
    }).catch((error) => {
      // An error happened.
    });
  }



  // These are the value that will be passed through Context API
  const value = {
    handleLogin,
    handleRegistration,
    handleLogout,
    userInfo
  }

  return (
    <html lang="en">
      <body className={inter.className}>


        <authContext.Provider value={value}>
          {children}
        </authContext.Provider>



      </body>
    </html>
  )
}
